import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // User Guide Sidebar - using directory auto-generation
  userGuideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'user-guide',
    },
  ],

  // Developer Guide Sidebar - custom structure
  developerGuideSidebar: [
    'developer-guide/getting-started',
    {
      type: 'category',
      label: 'Initial Setup',
      items: [
        'developer-guide/initial-setup/integrations/vtex-integration',
        'developer-guide/initial-setup/integrations/shopify-integration',
      ],
    },
    {
      type: 'category',
      label: 'Customization Reference',
      items: [
        'developer-guide/customization-reference/authentication',
        {
          type: 'category',
          label: 'Search API',
          items: [
            'developer-guide/customization-reference/search/overview',
            'developer-guide/customization-reference/search/detailed-search',
            'developer-guide/customization-reference/search/examples',
          ],
        },
        'developer-guide/customization-reference/ui-integration',
        'developer-guide/customization-reference/vm-builder',
      ],
    },
    {
      type: 'category',
      label: 'Analytics and Tracking',
      items: [
        'developer-guide/analytics-tracking/analytics/google-analytics',
        'developer-guide/analytics-tracking/analytics/google-tag-manager',
      ],
    },
    {
      type: 'category',
      label: 'Recommendations and Search Integration',
      items: [
        'developer-guide/recommendations-search/api-endpoints',
      ],
    },
  ],
};

export default sidebars;
